export const designation = [
    { key:1, value: "Accountant" },
    { key:2, value: "Administrative Assistant" },
    { key:3, value: "Business Analyst" },
    { key:4, value: "Chairman of the Board" },
    { key:5, value: "Chief Executive Officer" },
    { key:6, value: "Chief Financial Officer" },
    { key:7, value: "Chief Human Resources Officer" },
    { key:8, value: "Chief Information Officer" },
    { key:9, value: "Chief Information Security Officer" },
    { key:10, value: "Chief Marketing Officer" },
    { key:11, value: "Chief Operating Officer" },
    { key:12, value: "Chief Technology Officer" },
    { key:13, value: "Customer Service Representative" },
    { key:14, value: "Director" },
    { key:15, value: "Executive Assistant" },
    { key:16, value: "Finance Manager" },
    { key:17, value: "General Manager" },
    { key:18, value: "HR Manager" },
    { key:19, value: "IT Manager" },
    { key:20, value: "IT Support Specialist" },
    { key:21, value: "Line Manager" },
    { key:22, value: "Manager" },
    { key:23, value: "Marketing Coordinator" },
    { key:24, value: "Marketing Manager" },
    { key:25, value: "Operations Manager" },
    { key:26, value: "President" },
    { key:27, value: "Production Operator" },
    { key:28, value: "Project Manager" },
    { key:29, value: "Receptionist" },
    { key:30, value: "Sales Manager" },
    { key:31, value: "Sales Representative" },
    { key:32, value: "Security" },
    { key:33, value: "Supervisor" },
    { key:34, value: "Team Leader" },
    { key:35, value: "Vice President" },
]
