export const states=[
    { state: "Andhra Pradesh", abbreviation: "AP" },
    { state: "Arunachal Pradesh", abbreviation: "AR" },
    { state: "Assam", abbreviation: "AS" },
    { state: "Bihar", abbreviation: "BR" },
    { state: "Chhattisgarh", abbreviation: "CG" },
    { state: "Goa", abbreviation: "GA" },
    { state: "Gujarat", abbreviation: "GJ" },
    { state: "Haryana", abbreviation: "HR" },
    { state: "Himachal Pradesh", abbreviation: "HP" },
    { state: "Jharkhand", abbreviation: "JH" },
    { state: "Karnataka", abbreviation: "KA" },
    { state: "Kerala", abbreviation: "KL" },
    { state: "Madhya Pradesh", abbreviation: "MP" },
    { state: "Maharashtra", abbreviation: "MH" },
    { state: "Manipur", abbreviation: "MN" },
    { state: "Meghalaya", abbreviation: "ML" },
    { state: "Mizoram", abbreviation: "MZ" },
    { state: "Nagaland", abbreviation: "NL" },
    { state: "Odisha", abbreviation: "OR" },
    { state: "Punjab", abbreviation: "PB" },
    { state: "Rajasthan", abbreviation: "RJ" },
    { state: "Sikkim", abbreviation: "SK" },
    { state: "Tamil Nadu", abbreviation: "TN" },
    { state: "Telangana", abbreviation: "TS" },
    { state: "Tripura", abbreviation: "TR" },
    { state: "Uttar Pradesh", abbreviation: "UP" },
    { state: "Uttarakhand", abbreviation: "UK" },
    { state: "West Bengal", abbreviation: "WB" }
]
